export const ADD_REQUEST="ADD_REQUEST"
export const SET_REQUEST="SET_REQUEST"

export const LOADING='LOADING';
export const LOADING_HISTORY='LOADING_HISTORY';


export const AUTHENTICATE="AUTHENTICATE"
export const LOGOUT ="LOGOUT"
